/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.JOptionPane;
import java.sql.ResultSet;   
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
public class adminlogin extends javax.swing.JFrame {

    
  public adminlogin() {
        initComponents();
        this.setLocationRelativeTo(null);
  }
     table t=new table();
     Dashboard db=new Dashboard();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Text1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        loginB = new javax.swing.JButton();
        Text2 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        Text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text1ActionPerformed(evt);
            }
        });
        jPanel1.add(Text1);
        Text1.setBounds(380, 130, 170, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled-1 (3).png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 20, 280, 180);

        loginB.setBackground(new java.awt.Color(255, 255, 255));
        loginB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        loginB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBMouseEntered(evt);
            }
        });
        loginB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBActionPerformed(evt);
            }
        });
        jPanel1.add(loginB);
        loginB.setBounds(400, 240, 130, 40);

        Text2.setText("jPasswordField1");
        Text2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text2ActionPerformed(evt);
            }
        });
        jPanel1.add(Text2);
        Text2.setBounds(380, 180, 170, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2847441.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-20, 0, 620, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBActionPerformed
        PreparedStatement ps;
         ResultSet rs;
         
         String username=Text1.getText();
         String password=String.valueOf(Text2.getPassword());
         
         if(username.trim().equals("")){
             JOptionPane.showMessageDialog(rootPane,"Enter your Username To Login","Empty Username",2);
         }
         else if(password.trim().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Enter your Password To Login","Empty Password",2);  
         }
         else{
            MyConnection con = new MyConnection();
             String query="SELECT * FROM `login` WHERE `username`=? AND`password`=?";
             try {
                  ps= con.getConnection().prepareStatement(query);
                  ps.setString(1, username);
                  ps.setString(2, password);
                  rs=ps.executeQuery();
                  if(rs.next()){
                      
                JOptionPane.showMessageDialog(this,"username and password matched and you are logined as "+rs.getString("username"));
                 t.fill(db.dashboard);
                 this.setVisible(false);
                 db.setVisible(true);
                         }
            else{
                 JOptionPane.showMessageDialog(this, "username and password not matched");
                 }
             }catch (SQLException ex) {
                 Logger.getLogger(adminlogin.class.getName()).log(Level.SEVERE, null, ex);
             }
             
         }
         
    }//GEN-LAST:event_loginBActionPerformed

    private void loginBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBMouseClicked
        
    }//GEN-LAST:event_loginBMouseClicked

    private void loginBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBMouseEntered
       
    }//GEN-LAST:event_loginBMouseEntered

    private void Text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text1ActionPerformed

    private void Text2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminlogin().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Text1;
    private javax.swing.JPasswordField Text2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginB;
    // End of variables declaration//GEN-END:variables
}
